#!/bin/bash

set -e

find ~/Documents/work_stuff/notes/ | grep "[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_${1}_[0-9]\{2\}.[0-9]\{2\}.[0-9]\{2\}" | sort -k 1,1r

#vim ~/Documents/work_stuff/notes/${DATE3}/${DATE1}_${1}_${DATE2}.txt
