#!/bin/bash

DATE1=`date '+%Y-%m-%d'`
DATE2=`date '+%H.%M.%S'`
DATE3=`date '+%Y'`
DATE=${DATE1}_${DATE2}

NOTESDIR=NOTEDIR

cd $NOTESDIR && \
git add \
    $( \
        find . -type f | \
        grep -v '\.git' | \
        grep '\.txt$\|\.md$' \
    )

git commit -m "updated ${DATE}"
