#!/bin/bash

DATE1=`date '+%Y-%m-%d'`
DATE2=`date '+%H.%M.%S'`
DATE3=`date '+%Y'`

mkdir -p NOTEDIR/${DATE3}

date >> NOTEDIR/${DATE3}/${DATE1}_${1}_${DATE2}.txt
vim NOTEDIR/${DATE3}/${DATE1}_${1}_${DATE2}.txt
