#!/bin/bash

set -e

DATE1=`date '+%Y-%m-%d'`
DATE2=`date '+%H.%M.%S'`
DATE3=`date '+%Y'`

mkdir -p ~/Documents/work_stuff/notes/${DATE3}

date >> ~/Documents/work_stuff/notes/${DATE3}/${DATE1}_${1}_${DATE2}.txt

vim $(find ~/Documents/work_stuff/notes/ | grep "[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}_${1}_[0-9]\{2\}.[0-9]\{2\}.[0-9]\{2\}" | sort -k 1,1r)

#vim ~/Documents/work_stuff/notes/${DATE3}/${DATE1}_${1}_${DATE2}.txt
